version: '3'

services:
  app:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
  
  db:
    image: postgres
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: clbackdb